/* This file was generated by SableCC (http://www.sablecc.org/). */

package minipython.node;

import java.util.*;
import minipython.analysis.*;

public final class AAndcComparison extends PComparison
{
    private PComparison _lpar_;
    private PComparison _rpar_;

    public AAndcComparison()
    {
    }

    public AAndcComparison(
        PComparison _lpar_,
        PComparison _rpar_)
    {
        setLpar(_lpar_);

        setRpar(_rpar_);

    }
    public Object clone()
    {
        return new AAndcComparison(
            (PComparison) cloneNode(_lpar_),
            (PComparison) cloneNode(_rpar_));
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAAndcComparison(this);
    }

    public PComparison getLpar()
    {
        return _lpar_;
    }

    public void setLpar(PComparison node)
    {
        if(_lpar_ != null)
        {
            _lpar_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        _lpar_ = node;
    }

    public PComparison getRpar()
    {
        return _rpar_;
    }

    public void setRpar(PComparison node)
    {
        if(_rpar_ != null)
        {
            _rpar_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        _rpar_ = node;
    }

    public String toString()
    {
        return ""
            + toString(_lpar_)
            + toString(_rpar_);
    }

    void removeChild(Node child)
    {
        if(_lpar_ == child)
        {
            _lpar_ = null;
            return;
        }

        if(_rpar_ == child)
        {
            _rpar_ = null;
            return;
        }

    }

    void replaceChild(Node oldChild, Node newChild)
    {
        if(_lpar_ == oldChild)
        {
            setLpar((PComparison) newChild);
            return;
        }

        if(_rpar_ == oldChild)
        {
            setRpar((PComparison) newChild);
            return;
        }

    }
}
