/* This file was generated by SableCC (http://www.sablecc.org/). */

package minipython.node;

import java.util.*;
import minipython.analysis.*;

public final class AAssertStatement extends PStatement
{
    private PExpression _lpar_;
    private final LinkedList _rpar_ = new TypedLinkedList(new Rpar_Cast());

    public AAssertStatement()
    {
    }

    public AAssertStatement(
        PExpression _lpar_,
        List _rpar_)
    {
        setLpar(_lpar_);

        {
            this._rpar_.clear();
            this._rpar_.addAll(_rpar_);
        }

    }
    public Object clone()
    {
        return new AAssertStatement(
            (PExpression) cloneNode(_lpar_),
            cloneList(_rpar_));
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAAssertStatement(this);
    }

    public PExpression getLpar()
    {
        return _lpar_;
    }

    public void setLpar(PExpression node)
    {
        if(_lpar_ != null)
        {
            _lpar_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        _lpar_ = node;
    }

    public LinkedList getRpar()
    {
        return _rpar_;
    }

    public void setRpar(List list)
    {
        _rpar_.clear();
        _rpar_.addAll(list);
    }

    public String toString()
    {
        return ""
            + toString(_lpar_)
            + toString(_rpar_);
    }

    void removeChild(Node child)
    {
        if(_lpar_ == child)
        {
            _lpar_ = null;
            return;
        }

        if(_rpar_.remove(child))
        {
            return;
        }

    }

    void replaceChild(Node oldChild, Node newChild)
    {
        if(_lpar_ == oldChild)
        {
            setLpar((PExpression) newChild);
            return;
        }

        for(ListIterator i = _rpar_.listIterator(); i.hasNext();)
        {
            if(i.next() == oldChild)
            {
                if(newChild != null)
                {
                    i.set(newChild);
                    oldChild.parent(null);
                    return;
                }

                i.remove();
                oldChild.parent(null);
                return;
            }
        }

    }

    private class Rpar_Cast implements Cast
    {
        public Object cast(Object o)
        {
            PExpression node = (PExpression) o;

            if((node.parent() != null) &&
                (node.parent() != AAssertStatement.this))
            {
                node.parent().removeChild(node);
            }

            if((node.parent() == null) ||
                (node.parent() != AAssertStatement.this))
            {
                node.parent(AAssertStatement.this);
            }

            return node;
        }
    }
}
