/* This file was generated by SableCC (http://www.sablecc.org/). */

package minipython.node;

import java.util.*;
import minipython.analysis.*;

public final class ACommaModule extends PCommaModule
{
    private PModule _module_;
    private final LinkedList _identifier_ = new TypedLinkedList(new Identifier_Cast());

    public ACommaModule()
    {
    }

    public ACommaModule(
        PModule _module_,
        List _identifier_)
    {
        setModule(_module_);

        {
            this._identifier_.clear();
            this._identifier_.addAll(_identifier_);
        }

    }
    public Object clone()
    {
        return new ACommaModule(
            (PModule) cloneNode(_module_),
            cloneList(_identifier_));
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseACommaModule(this);
    }

    public PModule getModule()
    {
        return _module_;
    }

    public void setModule(PModule node)
    {
        if(_module_ != null)
        {
            _module_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        _module_ = node;
    }

    public LinkedList getIdentifier()
    {
        return _identifier_;
    }

    public void setIdentifier(List list)
    {
        _identifier_.clear();
        _identifier_.addAll(list);
    }

    public String toString()
    {
        return ""
            + toString(_module_)
            + toString(_identifier_);
    }

    void removeChild(Node child)
    {
        if(_module_ == child)
        {
            _module_ = null;
            return;
        }

        if(_identifier_.remove(child))
        {
            return;
        }

    }

    void replaceChild(Node oldChild, Node newChild)
    {
        if(_module_ == oldChild)
        {
            setModule((PModule) newChild);
            return;
        }

        for(ListIterator i = _identifier_.listIterator(); i.hasNext();)
        {
            if(i.next() == oldChild)
            {
                if(newChild != null)
                {
                    i.set(newChild);
                    oldChild.parent(null);
                    return;
                }

                i.remove();
                oldChild.parent(null);
                return;
            }
        }

    }

    private class Identifier_Cast implements Cast
    {
        public Object cast(Object o)
        {
            PIdentifier node = (PIdentifier) o;

            if((node.parent() != null) &&
                (node.parent() != ACommaModule.this))
            {
                node.parent().removeChild(node);
            }

            if((node.parent() == null) ||
                (node.parent() != ACommaModule.this))
            {
                node.parent(ACommaModule.this);
            }

            return node;
        }
    }
}
