/* This file was generated by SableCC (http://www.sablecc.org/). */

package minipython.node;

import java.util.*;
import minipython.analysis.*;

public final class AManyArrayExpression extends PArrayExpression
{
    private PArrayExpression _arrayExpression_;
    private PExpression _expression_;

    public AManyArrayExpression()
    {
    }

    public AManyArrayExpression(
        PArrayExpression _arrayExpression_,
        PExpression _expression_)
    {
        setArrayExpression(_arrayExpression_);

        setExpression(_expression_);

    }
    public Object clone()
    {
        return new AManyArrayExpression(
            (PArrayExpression) cloneNode(_arrayExpression_),
            (PExpression) cloneNode(_expression_));
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAManyArrayExpression(this);
    }

    public PArrayExpression getArrayExpression()
    {
        return _arrayExpression_;
    }

    public void setArrayExpression(PArrayExpression node)
    {
        if(_arrayExpression_ != null)
        {
            _arrayExpression_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        _arrayExpression_ = node;
    }

    public PExpression getExpression()
    {
        return _expression_;
    }

    public void setExpression(PExpression node)
    {
        if(_expression_ != null)
        {
            _expression_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        _expression_ = node;
    }

    public String toString()
    {
        return ""
            + toString(_arrayExpression_)
            + toString(_expression_);
    }

    void removeChild(Node child)
    {
        if(_arrayExpression_ == child)
        {
            _arrayExpression_ = null;
            return;
        }

        if(_expression_ == child)
        {
            _expression_ = null;
            return;
        }

    }

    void replaceChild(Node oldChild, Node newChild)
    {
        if(_arrayExpression_ == oldChild)
        {
            setArrayExpression((PArrayExpression) newChild);
            return;
        }

        if(_expression_ == oldChild)
        {
            setExpression((PExpression) newChild);
            return;
        }

    }
}
