/* This file was generated by SableCC (http://www.sablecc.org/). */

package minipython.node;

import java.util.*;
import minipython.analysis.*;

public final class AMultiModule extends PModule
{
    private PIdentifier _identifier_;
    private PModule _module_;

    public AMultiModule()
    {
    }

    public AMultiModule(
        PIdentifier _identifier_,
        PModule _module_)
    {
        setIdentifier(_identifier_);

        setModule(_module_);

    }
    public Object clone()
    {
        return new AMultiModule(
            (PIdentifier) cloneNode(_identifier_),
            (PModule) cloneNode(_module_));
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAMultiModule(this);
    }

    public PIdentifier getIdentifier()
    {
        return _identifier_;
    }

    public void setIdentifier(PIdentifier node)
    {
        if(_identifier_ != null)
        {
            _identifier_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        _identifier_ = node;
    }

    public PModule getModule()
    {
        return _module_;
    }

    public void setModule(PModule node)
    {
        if(_module_ != null)
        {
            _module_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        _module_ = node;
    }

    public String toString()
    {
        return ""
            + toString(_identifier_)
            + toString(_module_);
    }

    void removeChild(Node child)
    {
        if(_identifier_ == child)
        {
            _identifier_ = null;
            return;
        }

        if(_module_ == child)
        {
            _module_ = null;
            return;
        }

    }

    void replaceChild(Node oldChild, Node newChild)
    {
        if(_identifier_ == oldChild)
        {
            setIdentifier((PIdentifier) newChild);
            return;
        }

        if(_module_ == oldChild)
        {
            setModule((PModule) newChild);
            return;
        }

    }
}
