/* This file was generated by SableCC (http://www.sablecc.org/). */

package minipython.node;

import minipython.analysis.*;

public final class TDict extends Token
{
    public TDict()
    {
        super.setText("dict");
    }

    public TDict(int line, int pos)
    {
        super.setText("dict");
        setLine(line);
        setPos(pos);
    }

    public Object clone()
    {
      return new TDict(getLine(), getPos());
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTDict(this);
    }

    public void setText(String text)
    {
        throw new RuntimeException("Cannot change TDict text.");
    }
}
